Document: athrill-rh850f1x
Title: Debian athrill-rh850f1x Manual
Author: <insert document author here>
Abstract: This manual describes what athrill-rh850f1x is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/athrill-rh850f1x/athrill-rh850f1x.sgml.gz

Format: postscript
Files: /usr/share/doc/athrill-rh850f1x/athrill-rh850f1x.ps.gz

Format: text
Files: /usr/share/doc/athrill-rh850f1x/athrill-rh850f1x.text.gz

Format: HTML
Index: /usr/share/doc/athrill-rh850f1x/html/index.html
Files: /usr/share/doc/athrill-rh850f1x/html/*.html
