# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    env:
      DEBFULLNAME: "mikoto2000"
      DEBMAIL: "mikoto2000@gmail.com"
      LONGNAME: "mikoto2000"
      USER: "mikoto2000"
      TZ: "Azia/Tokyo"

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      # Runs a set of commands using the runners shell
      - name: build deb package
        id: build-deb
        run: |
          # 必要なパッケージのインストール
          sudo apt-get update
          sudo apt-get install -y build-essential git-buildpackage cdbs git

          sudo git config --global user.name ${USER}
          sudo git config --global user.email ${DEBMAIL}

          sudo debian/rules binary

          VERSION=debian/$(cat debian/changelog | sed -e 's/^.*(\(.*\)).*$/\1/g' | head -1)
          echo "::set-output name=VERSION::${VERSION}"

          git push origin ${BUILD_TIME}
          git tag ${VERSION}
          git push origin --tags

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: debian/${{ steps.build-deb.outputs.VERSION }}
          release_name: ${{ steps.build-deb.outputs.VERSION }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

